### ISSUE TITLE
Add Total Laps into telemetry open screen

### ISSUE THREAD

**Issue by Briz0wns** [stevendaniluk/SDMotecWorkspace#1]
Hi,

it's very useful to see total laps per telemetry files when you do select them. This is handled in workspace rootfolder in file "LoggedDataOpen.xml"

String to enable is this:
 <Column Keyword="Total Laps" Flags="1"/>

I will try to do pull request but please consider this is my 1st time with github.

**Comment by stevendaniluk** [comment]
Addressed in #2
