### ISSUE TITLE
Adding Track Maps

### ISSUE THREAD

**Issue by BrokenHypocrite** [stevendaniluk/SDMotecWorkspace#5]
Hi. I have some .ld files I wrote from UPD telemetry data from a sim racing game. Everything opens fine in MoTeC I2 Pro, but I am having some trouble with the Track Maps. I don't have real GPS data, just world position x, y, z data points. I do have Lateral gforce and Speed data, but when I try to generate a track from this data it usually comes out looking far off from the actual track. It looks as though if I have a .mt2 file for the track (name matching the venue in the header data) that I2 Pro will map it correctly to the track. Is there any way to generate .mt2 track files. There are many tracks I can not find existing .mt2 files for.

Appreciate any insight you have to give!

**Comment by stevendaniluk** [comment]
I've never attempted to generate `.mt2` files on my own, or even dug into the file format so I can't speak to how easy or difficult that may be.

Can you post what the generated track map looks like when you use speed and lateral acceleration data? Maybe also include a plot of those variables as well. I've used that method quite a bit and it tends to work quite well.

**Comment by BrokenHypocrite** [comment]
Appreciate the response. I ended up projecting my world position data onto the globe to get pseudo GPS coords and this worked really well. I'll close this "issue" out now. For those interested I just did this:

lat = ref_lat + (x_pos_meters / r) * (180 / pi)            
lon = ref_lon + (y_pos_meters / r) * (180 / pi) / cos(ref_lat * pi/180)

Note: r = 6371000 meters, ref_lat and ref_lon I used as the real life coords of the start finish line. Depending on your position data from the game you may need to rotate it to line up with the real life orientation of the track. The x_pos_meters and y_pos_meters where actually Z and X position data respectively and not all the tracks were oriented correctly.
